---
title: "Make Panel"
format: 
  html:
    page-layout: full
    self-contained: true
    toc: true
    toc-depth: 3
execute: 
  warning: false

---

## Code Status

In progress

## Notes

Reformat clean data file into long format for feature creation

## Set up

```{r setup, warning=FALSE}
#| include: false

options(conflicts.policy = "depends.ok")
library(tidyverse) 

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_gps.R?raw=true")

path_processed <- format_path("optimize/data_processed")

```



Open the cleaned dataframe and remove variables that aren't needed for modelling
```{r}

panel_clean <- read_csv(tibble(path = list.files(str_c(path_processed, "/panel"), pattern = "^panel_clean_", full.names = TRUE)) |> mutate(mdate = file.mtime(path)) |> filter(mdate == max(mdate)) |> pull(path)) |>
  select(-c(response_set:ip_address,
            recipient_last_name:q_quality_score, 
            q_ballot_box_stuffing,
            message_order:block_order_li,
            blocknum:survey_order,
            q_quality_timestamp:consent_agree, 
            q_recaptcha_score:eligible_health, 
            q12_grocer_1_text,q12_grocer_2_text,
            contains("timing"),
            ends_with("attention"),
            `_8`,
            id_location_1_text, id_location_2_text,
            starts_with("ro_"),
            location_latitude:location_accuracy,
            q_recaptcha_score:eligible_health,
            tone_message_ro:block_4)) |>
  mutate(subid = row_number()) |>
  relocate(subid) |>
  select(-response_id) |>
  glimpse()

```

Combine all messages into a single column, pivoting longer so person has 30 rows
```{r}



panel_long <- panel_clean |>
  pivot_longer(cols= `1_hi_1_fl`:`4_li_10_in`, values_to = "message_rating", names_to = "message_type") |>
  distinct() |>
  filter(!is.na(message_rating)) |>
  separate(message_type, sep ="_", into = c("survey_version", "context", "q_num", "tone_style")) |> 
  mutate(style = substr(tone_style, 1,1)) |>
  mutate(tone = substr(tone_style, 2,2)) |>  
  mutate(style = if_else(style == "f", "formal", "informal")) |>
  mutate(tone = case_when(tone == "l" ~ "legitimizing",
                          tone== "n" ~ "norms",
                          tone== "s" ~ "self_efficacy",
                          tone== "a" ~ "acknowledging",
                          tone== "v" ~ "value_affirmation")) |>
    mutate(context = case_when(context == "hi" ~ "high_increasing",
                          context== "hd" ~ "high_decreasing",
                          context== "li" ~ "low_increasing")) |>
    select(-q_num, -tone_style)  |>                   
  glimpse()


```

Save out
```{r}
panel_long |> write_csv(file.path(path_processed, "panel/panel_long.csv"))
```

