## Message tone
* Participant characteristics
* Covariate?
* Measured at baseline

### Response Scale

- Strongly disagree
- Disagree
- Slightly disagree
- Neutral 
- Slightly agree
- Agree
- Strongly agree

### Items

For the next series of questions, we will describe different ways that people might communicate with you when you need help. We want to know about *your* specific preferences. It is fine to like one or many of the communication styles we describe below. Please rate each communication style independently. Simply select how much you like each communication style when you need help.

**When I need help, I want to be talked to by someone who...**

<!--*Legitimizing*

Current LLM prompt:
The message should use a 'Legitimizing' approach by emphasizing that experiencing challenges, doubts, and strong feelings during recovery is normal and acceptable. Focus on conveying that these experiences are valid and expected, while maintaining a supportive and validating tone that reduces shame, blame, and isolation. Avoid naming specific emotions like guilt or fear and keep the overall message affirming.-->
1. ...lets me know that my feelings and experiences are reasonable. I want to be reminded that it is okay to feel this way and not have my feelings and experiences minimized or dismissed.

<!--
*Self-Efficacy*

Current LLM prompt:
The message should use a 'Self-Efficacy' approach by emphasizing the individual's strengths and abilities to engage effectively with the app. Highlight that they have the capacity to stick with the app's features, navigate recovery challenges, and build on their past successes. Make the overall tone optimistic and focused on their personal capability and self-efficacy to stick with the app or improve.
-->
2. ...makes me feel capable. I want to be reminded that I have what it takes to keep going and the skills to succeed.

<!--
*Acknowledging*

Current LLM prompt:
The message should use an 'Acknowledgement of Feelings' approach by demonstrating attentive listening and encouraging emotional exploration without imposing interpretations. Show genuine interest in the individual's emotional experience, offer thoughtful hypotheses about their feelings without prescriptive language, reflect their emotional responses accurately, and encourage continued reflection in a non-interrogative manner. Keep the overall tone validating and focused on self-exploration.
-->
3. ...listens to my feelings and experiences. I want to be reminded that I have been heard and be encouraged to reflect on my emotions.

<!--
*Value Affirmation*

Current LLM prompt:
The message should use a 'Value Affirmation' approach by highlighting the person's deeper life priorities (such as family, career, health, or personal well-being) and connecting these values to engaging with the app. Emphasize how taking steps in recovery can support those values and strengthen their sense of purpose and work to affirm this values. Encourage the individual to see how the app aligns with what matters most to them.

-->
4. ...helps me connect with what matters most to me. I want to be reminded to think about what’s important in my life and why I keep going.

<!--
*Norms*

Current LLM prompt:
The message should use a 'Norms' approach by emphasizing how others with comparable experiences have successfully used the app to reduce cravings and manage stress, and by highlighting that the person is not alone in this process. Acknowledge that similar individuals have also faced challenges but found encouragement and progress through the app. Reinforce a sense of belonging and shared progress.
-->
5. ...helps me remember that others have had similar feelings and experiences. I want to be reminded that others have had comparable struggles and that mine are not unusual.

---

## Message style (formal versus informal)

### Response Scale

- Strongly prefer formal
- Moderately prefer formal
- Slightly prefer formal
- Slightly prefer informal
- Moderately prefer informal
- Strongly prefer informal

### Item
Next, we want to know what kinds of messages you would like to receive from our <!--recovery support app--> if you were using it.  We can write these message to be more **formal** (for example, professional or polite -- like how your doctor might speak to you) or **informal** (for example, casual or conversational -- like how your friend might message you).  We want to know *your* specific preferences about how formal vs. informal these messages should be.


### Source

In-house measure
