---
title: "Survey Introduction"
format: html
---

## Survey Introduction

The purpose of this survey is to better understand what types of supportive messages people might like to receive in the context of a mental health app designed to promote abstinence from alcohol. We are interested in understanding what styles of messages people like and how personal traits may impact those preferences. There are no "right" or "wrong" answers.

For this survey, imagine that you are in recovery from alcoholism and you are trying to not drink at all. You have downloaded an app on your phone designed to help you with your recovery journey. This app will give you personalized support messages each day to help you with your recovery. 

This survey has three parts. First, we will ask you some questions about yourself. Then, we will ask you to tell us about your general preferences about the style of the support messages you might like to receive from this app. Lastly, we will ask you to rate how much you like specific examples of support messages from the app.

We expect that the total survey will take about XX minutes to complete.  We thank you for your time and careful responding in this survey.

## Context section introduction

In this final section of the survey, we will ask you to imagine that you are in recovery from alcoholism, trying not to drink any alcohol, and receiving specific support messages in different scenarios.

In these scenarios, the support messages from the recovery app will be providing you with feedback on two things: your risk level for drinking that day and how that risk level might have changed over the last two weeks.  For each specific support message, you will rate how helpful you would find that message in that particular scenario.

## Specific context introduction

> This is an example of what the context description could look like using the high and increasing scenario.

For the following messages, imagine that you have a high risk of drinking that day and that your daily risk for drinking has been increasing over the past two weeks. Please rate how helpful you would find each support message in this scenario.
