---
title: "Clean GPS data for llmpanel"
format: html
editor: visual
---

## Setup

```{r}
#| include: false

options(conflicts.policy = "depends.ok")
library(tidyverse)
library(geosphere)

source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

path_processed <- format_path("llmpanel/data_processed")
```

```{r}
panel <- read_csv(here::here(path_processed, "panel.csv"))
gps_info <- read_csv(here::here(path_processed, "gps_info.csv"))
```

```{r}
panel <- panel |> 
  left_join(gps_info, by = "response_id")
```

```{r}
# Separate respondents with updated grocery info (valid + manually rejected)
panel_510 <- panel |>
  filter(response_id %in% gps_info$response_id)

panel_510 <- panel_510 |> 
  mutate(
    
#   Distance from city/state to IP address
    gps_city_to_ip = distHaversine(p1 = cbind(location_longitude, location_latitude),
                                   p2 = cbind(city_longitude, city_latitude)) / 1000,
    
#   Distance from city/state to grocery store
    gps_city_to_grocery = distHaversine(p1 = cbind(location_longitude, location_latitude),
                                        p2 = cbind(grocery_longitude, grocery_latitude)) / 1000,

#   Take the shortest of these two differences
    gps_diff = pmin(gps_city_to_ip, gps_city_to_grocery, na.rm = TRUE))

# Return result to full panel

panel_gps <- panel_510 |>
  select(response_id, gps_diff)

panel <- panel |>
  left_join(panel_gps, by = "response_id")

# Save changes to file
panel |> write_csv(here::here(path_processed,"panel.csv"))
```
