---
title: "Analyze performance for `r params$algorithm` in `r params$version` "
author: "John Curtin" 
date: "`r lubridate::today()`"
format: 
  html:
    toc: true 
    toc_depth: 2
    embed-resources: true
editor_options: 
  chunk_output_type: console
params:
  version: "v6"
  algorithm: "glmnet"
---

## Notes

This script can be rendered in terminal as follows:  `quarto render mak_best_config.qmd -o [outputname].html  -P version:v1`

# Setup 
```{r}
#| include: false

library(tidyverse)
source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
source("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")

path_in <- format_path(str_c("llmpanel/chtc/train_", 
                                 params$version, "/output"))
path_out <- format_path("llmpanel/data_processed")

theme_set(theme_classic()) 
```

Read in data
```{r}
folds <- read_csv(here::here(path_in, 
                         str_c("batch_results_", params$version, ".csv")), 
              show_col_types = FALSE) |> 
  arrange(config_num, outer_split_num, inner_split_num) |> 
  glimpse()
```

```{r}
folds |> tab(outer_split_num) |> print(n = Inf)
folds |> tab(inner_split_num) |> print(n = Inf)
folds |> tab(hp1)
folds |> tab(hp2)
folds |> tab(hp3)
folds |> tab(feature_set)
# folds |> tab (config_num) |> view()
```

## Overall Performance

Calculate median performance metrics 
```{r}
folds_mean <- folds |>
  group_by(feature_set, hp1, hp2, hp3) |>
  summarise(
    rsq = mean(rsq),
    mae = mean(mae),
    n = n(),
   .groups = "drop")

best <- folds_mean |> 
  group_by(feature_set) |>
  arrange(desc(rsq)) |> 
  slice_head(n = 1)

best
```

Histogram of folds
```{r}
# if (params$algorithm == "glmnet") {
#   d_hist <- folds |> 
#     filter(feature_set == best$feature_set,
#            hp1 == best$hp1,
#            hp2 == best$hp2) |> 
#     arrange(split_num) |> 
#   select(rsq) 
#   
# } else {
#   d_hist <- folds |> 
#     filter(feature_set == best$feature_set,
#            hp1 == best$hp1,
#            hp2 == best$hp2,
#            hp3 == best$hp3) |> 
#     arrange(split_num) |> 
#   select(rsq) 
# }
#   
#   
# d_hist |>  
#   ggplot(aes(x = rsq)) + 
#     geom_histogram(breaks = seq(0, .4, by = 0.01), 
#                    color = "black", fill = "blue") +
#     theme(plot.title = element_text(hjust = 0.5, size = 24), 
#           axis.text = element_text(size = 18), 
#           axis.title = element_text(size = 20))
```

Write out file all
```{r}
folds_mean |> 
  group_by(feature_set) |> 
  arrange(desc(rsq)) |>
  write_csv(here::here(path_out,
                       str_c("configs_mean_", params$version, ".csv")))

best |> 
  arrange(desc(rsq)) |>
  write_csv(here::here(path_out,
                       str_c("configs_best_", params$version, ".csv")))
```