---
title: "test join"
format: html
editor: visual
---

```{r}
library(tidyverse)
panel <- read_csv("C:/Users/Andrew/Desktop/panel_510.csv")
grocery_codes <- read_csv("C:/Users/Andrew/Desktop/grocer_codes.csv")
```

```{r}
codes_long <- grocery_codes |>
  pivot_longer(everything(), names_to = "grocery_code", values_to = "subid") |> 
  filter(!is.na(subid)) |> 
  relocate(subid)
```

```{r}
panel <- panel |>
  left_join(codes_long, by = "subid")
```

```{r}
panel <- panel |> 
  relocate(grocery_code)
```

```{r}
grocer_gps <- readRDS("C:/Users/Andrew/Desktop/grocer_gps_510.rds")
```

```{r}
extract_field <- function(gps_list, i, field) {
  res <- tryCatch(gps_list[[i]]$results[[1]], error = function(e) NULL)
  switch(field,
    formatted_address = if (is.null(res)) NA_character_ else res$formatted_address %||% NA_character_,
    lat               = if (is.null(res)) NA_real_      else res$geometry$location$lat %||% NA_real_,
    lng               = if (is.null(res)) NA_real_      else res$geometry$location$lng %||% NA_real_
  )
}
panel <- panel |>
  mutate(
    ggmap_grocer_address = map_chr(
      seq_along(grocer_gps),
      ~extract_field(grocer_gps, .x, "formatted_address")),
    
    ggmap_latitude = map_dbl(
      seq_along(grocer_gps),
      ~extract_field(grocer_gps, .x, "lat")),
    
    ggmap_longitude = map_dbl(
      seq_along(grocer_gps),
      ~extract_field(grocer_gps, .x, "lng"))
  )
```

```{r}
address_fix <- read_csv("C:/Users/Andrew/Desktop/grocery sorts - address fix.csv")
grocery_fixes <- read_csv("C:/Users/Andrew/Desktop/grocery_fixes.csv")
```

```{r}
grocery_fixes <- grocery_fixes |>
  left_join(address_fix, by = "address")
```

```{r}
grocery_fixes <- grocery_fixes |> 
  relocate(subid) |> 
  rename(
    update_longitude = lon,
    update_latitude = lat,
    update_address = address
  )
```

```{r}
grocery_fixes <- grocery_fixes |> rename(question_rid = response_id)
```

```{r}
inv <- grocery_fixes |> 
  filter(n() > 1, .by = subid)

grocery_fixes <- grocery_fixes |> 
  slice_head(n = 1, by = subid)
```

```{r}
panel <- panel |> 
  left_join(grocery_fixes, by = "subid")
```

```{r}
colnames(panel)

panel_grocery <- panel |> select(subid, response_id,
                                 q12_grocer_1, q12_grocer_2,
                                 id_location_1, id_location_2,
                                 ggmap_grocer_address,
                                 grocery_code,
                                 update_address,
                                 ggmap_latitude, ggmap_longitude,
                                 update_longitude, update_latitude
                                 )
```

```{r}
panel_grocery <- panel_grocery |> 
  mutate(final_address = coalesce(update_address, ggmap_grocer_address),
         grocery_latitude = coalesce(update_latitude, ggmap_latitude),
         grocery_longitude = coalesce(update_longitude, ggmap_longitude)) |> 
  relocate(final_address, .after = update_address)
```

```{r}
grocery_info <- panel_grocery |> 
  select(response_id, grocery_code, final_address, grocery_latitude, grocery_longitude)
```

```{r}
grocery_info |> write_csv("C:/Users/Andrew/Desktop/grocery_info.csv")-
```
