---
title: "Model evaluation"
author: "John Curtin"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 2
format:
  html:
    embed-resources: true
editor_options: 
  chunk_output_type: console
params:
  version: "v3"
---

## Setup 
```{r}
#| include: false

library(tidyverse)
library(tidyposterior)
options(conflicts.policy = "depends.ok")

source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
source("https://github.com/jjcurtin/lab_support/blob/main/my_skim.R?raw=true")

path_in <- format_path(str_c("llmpanel/chtc/train_", 
                                 params$version, "/output"))
path_out <- format_path("llmpanel/data_processed")
theme_set(theme_classic()) 
```

## Fold data
```{r}
folds <- read_csv(here::here(path_in, 
                         str_c("batch_results_", params$version, ".csv")), 
              show_col_types = FALSE) |> 
  glimpse()

best <- folds |>
  group_by(feature_set, hp1, hp2, hp3) |>
  summarise(
    rsq = median(rsq),
    mae = median(mae),
    n = n(),
   .groups = "drop") |> 
  group_by(feature_set) |>
  arrange(mae) |> 
  slice_head(n = 1)

folds_base <- folds |> 
  filter(feature_set == "base") |> 
  filter(hp1 == best |> filter(feature_set == "base") |> pull(hp1)) |> 
  filter(hp2 == best |> filter(feature_set == "base") |> pull(hp2)) |> 
  filter(hp3 == best |> filter(feature_set == "base") |> pull(hp3)) |> 
  arrange(outer_split_num, inner_split_num)
folds_dem <- folds |> 
  filter(feature_set == "dem") |> 
  filter(hp1 == best |> filter(feature_set == "dem") |> pull(hp1)) |> 
  filter(hp2 == best |> filter(feature_set == "dem") |> pull(hp2)) |> 
  filter(hp3 == best |> filter(feature_set == "dem") |> pull(hp3)) |> 
  arrange(outer_split_num, inner_split_num)
folds_pref <- folds |> 
  filter(feature_set == "pref") |> 
  filter(hp1 == best |> filter(feature_set == "pref") |> pull(hp1)) |> 
  filter(hp2 == best |> filter(feature_set == "pref") |> pull(hp2)) |> 
  filter(hp3 == best |> filter(feature_set == "pref") |> pull(hp3)) |>  
  arrange(outer_split_num, inner_split_num)

# Tibbles for posterior analysis
folds_mae <-folds_base |> 
  select(id = outer_split_num, id2 = inner_split_num, Baseline = mae) |> 
  mutate(id = ceiling(id / 5)) |> 
  mutate(Demographics = folds_dem$mae) |> 
  mutate(Preferences = folds_pref$mae)

folds_rsq <-folds_base |> 
  select(id = outer_split_num, id2 = inner_split_num, Baseline = rsq) |> 
  mutate(id = ceiling(id / 5)) |> 
  mutate(Demographics = folds_dem$rsq) |> 
  mutate(Preferences = folds_pref$rsq)
```

## RSQ

```{r}
#| output: false
 
# Repeated CV (id = repeat, id2 = fold within repeat)
# with a common variance:  statistic ~ model + (model | id2/id)
set.seed(101)
pp_rsq <- folds_rsq |> 
  perf_mod(formula = statistic ~ model + (1 | id2/id),
         # increased iteration from 2000 to fix divergence issues
         transform = tidyposterior::logit_trans,  # for skewed & bounded RSQ 
         iter = 3000, chains = 4, adapt_delta = .9, 
         family = gaussian)  
```

Model contrasts
```{r}
pp_rsq |>
  contrast_models(list("Preferences", "Demographics"), 
                  list("Demographics", "Baseline")) |> 
  summary(size = 0)  |> 
  select(contrast, probability, mean, lower, upper)
```

Tidy posterior object
```{r}
pp_tidy_rsq <- pp_rsq |> 
  tidy(seed = 123) 
```

Histogram by model
```{r}
pp_tidy_rsq |> 
  ggplot(aes(x = posterior)) +
  geom_histogram(binwidth = 50) +
  xlab("R-Squared") +
  facet_wrap(vars(model), nrow = 3)
```

Stats per model
```{r}
q = c(.025, .5, .975)
pp_tidy_rsq |> 
  group_by(model) |> 
  summarize(pp_median = quantile(posterior, probs = q[2]),
            pp_lower = quantile(posterior, probs = q[1]), 
            pp_upper = quantile(posterior, probs = q[3])) |> 
  mutate(model = factor(model)) |> 
  arrange(model)
```


## MAE

```{r}
#| output: false

# Repeated CV (id = repeat, id2 = fold within repeat)
# with a common variance:  statistic ~ model + (model | id2/id)
set.seed(101)
pp_mae <- folds_mae |> 
  perf_mod(formula = statistic ~ model + (1 | id2/id),
         # increased iteration from 2000 to fix divergence issues
         iter = 4000, chains = 4, adapt_delta = .9, 
         family = gaussian)  
```

Model contrasts
```{r}
pp_mae |>
  contrast_models(list("Preferences", "Demographics"), 
                  list("Demographics", "Baseline")) |> 
  summary(size = 0)  |> 
  select(contrast, probability, mean, lower, upper) |> 
  mutate(probability = 1 - probability)
```

```{r}
pp_tidy_mae <- pp_mae |> 
  tidy(seed = 123) 
```

```{r}
pp_tidy_mae |> 
  ggplot(aes(x = posterior)) +
  geom_histogram(binwidth = 50) +
  xlab("Mean Absolute Error") +
  facet_wrap(vars(model), nrow = 3)
```

```{r}
q = c(.025, .5, .975)
pp_tidy_mae |> 
  group_by(model) |> 
  summarize(pp_median = quantile(posterior, probs = q[2]),
            pp_lower = quantile(posterior, probs = q[1]), 
            pp_upper = quantile(posterior, probs = q[3])) |> 
  mutate(model = factor(model)) |> 
  arrange(model)
```